---

- name: Java | Install OpenJDK Implementation
  include: install_openjdk.yml
  when: java_implementation == 'openjdk'
  tags:
    - install

- name: Java | Install OracleJDK Implementation using distributed binaries
  include: install_oraclejdk.yml
  when: java_implementation == 'oraclejdk'
  tags:
    - install
