---

- name: JAVA | Install Oracle Implementation
  include: install_oracle.yml
  when: java_implementation == 'oracle'
  tags:
    - install

- name: JAVA | Install OpenJDK Implementation
  include: install_openjdk.yml
  when: java_implementation == 'openjdk'
  tags:
    - install
